# No '/' after dir name !
[structure]
SRC_DIR = "src"
PYPROJECT_TOML = "pyproject.toml"
POETRY_LOCK = "poetry.lock"

[db.postgres]
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "changethis"
POSTGRES_DB = "web_app"
POSTGRES_HOST = "db_postgres"  # Specify as in Docker network
POSTGRES_PORT = 5432

[db.sqlalchemy]
SQLA_ECHO = false
SQLA_ECHO_POOL = false
SQLA_POOL_SIZE = 50
SQLA_MAX_OVERFLOW = 10
