services:
  web_app_db_pg:
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    container_name: ${POSTGRES_HOST}
    image: postgres:16-alpine
    shm_size: 128mb
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ${PYPROJECT_TOML}
        - ${POETRY_LOCK}
        - ${UVICORN_PORT}
      target: runtime
    image: web_app:latest
    env_file:
      - .env
    environment:
      PYTHONPATH: "/app/${SRC_DIR}"
    ports:
      - "${UVICORN_PORT}:${UVICORN_PORT}"
    volumes:
      - ./${SRC_DIR}:/app/${SRC_DIR}
      - ./${CONFIG_TOML}:/app/${CONFIG_TOML}
      - ./.env:/app/.env
    depends_on:
      - web_app_db_pg
    command: [ "sh", "scripts/docker-compose/run_server.sh" ]

volumes:
  pgdata:
